defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: gendo
  password:
  pool: 35

development:
  <<: *defaults
  database: gendo

test:
  <<: *defaults
  database: gendo_test

# NOTE will be overriden by heroku configuration.
production:
  <<: *defaults
  database: gendo_production
